on:
  schedule:
    # At 01:00.
    - cron:  '01 13 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.zaproxy.org/'
          docker_name: 'owasp/zap2docker-weekly'
          cmd_options: '-z "-config view.locale=fr_FR"'
          # locale: 'fr_FR'
